version: 2
updates:
- package-ecosystem: terraform
  directory: "/gcp/"
  schedule:
    interval: daily
    time: "11:00"
- package-ecosystem: terraform
  directory: "/aws/"
  schedule:
    interval: daily
    time: "11:00"